- name: Send Success Email
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: smtp.gmail.com
    server_port: 465
    username: $EMAIL_USER
    password: $EMAIL_PASS
    subject: "Build Success"
    body: "Your GitHub Actions workflow completed successfully!"
    to: nasseor4@gmail.com
    from: $EMAIL_USER
    secure: true
